# Generated by Django 5.2.4 on 2025-07-09 11:33
from django.db import migrations, models


def assign_default_slugs(apps, schema_editor):
    import uuid
    Wishlist = apps.get_model('wishlist', 'Wishlist')
    used = set()
    for wishlist in Wishlist.objects.all():
        slug = uuid.uuid4()
        while slug in used:
            slug = uuid.uuid4()
        used.add(slug)
        wishlist.slug = slug
        wishlist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.UUIDField(default=None, null=True, editable=False),
        ),
        migrations.RunPython(assign_default_slugs),
    ]
