# Generated by Django 5.2.4 on 2025-07-09 11:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
