version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.prod

  web:
    build: .
    container_name: wisher_web
    depends_on:
      - db
    volumes:
      - ./static:/app/staticfiles
    env_file:
      - .env.prod

  frontend:
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
      - frontend_dist:/usr/share/nginx/html:ro
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: wisher_frontend
    depends_on:
      - web
    env_file:
      - ./frontend/.env.prod

volumes:
  postgres_data:
  frontend_dist: